# Generated by Django 5.1.5 on 2025-01-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
    ]
